### ISSUE TITLE
Uncaught except GET /jupyter/user/USERNAME/api/nbconvert ?

### ISSUE THREAD

**Issue by radumas** [timkpaine/lantern#185]
I'm not entirely sure these are related... but they all show up as one block when running `jupyterhub --debug`.

I installed with `jupyter labextension install pylantern`

I'm on jupyterlab-sql 0.1.4 with JupyterLab 0.35.4with JupyterHub0.9.4` in Ubuntu 16.04 and the below appears in the log. Thoughts?

```python
[E 2019-03-11 15:53:06.977 SingleUserNotebookApp web:1670] Uncaught exception GET /jupyter/user/USERNAM/api/nbconvert?1552333986883 (ip)
    HTTPServerRequest(protocol='http', host='ip', method='GET', uri='/jupyter/user/USERNAME/api/nbconvert?1552333986883', version='HTTP/1.1', remote_ip='ip')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/nbconvert/handlers.py", line 20, in get
        exporter_class = base.get_exporter(exporter_name)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/base.py", line 98, in get_exporter
        return entrypoints.get_single('nbconvert.exporters', name).load()
      File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/usr/local/lib/python3.5/dist-packages/lantern/__init__.py", line 2, in <module>
        from .data import *
      File "/usr/local/lib/python3.5/dist-packages/lantern/data/__init__.py", line 3, in <module>
        from .other import person, people, company, companies, ticker, currency, trades, superstore
      File "/usr/local/lib/python3.5/dist-packages/lantern/data/other.py", line 4, in <module>
        import mimesis
      File "/usr/local/lib/python3.5/dist-packages/mimesis/__init__.py", line 10, in <module>
        from mimesis.providers import *
      File "/usr/local/lib/python3.5/dist-packages/mimesis/providers/__init__.py", line 5, in <module>
        from mimesis.providers.base import BaseProvider, BaseDataProvider
      File "/usr/local/lib/python3.5/dist-packages/mimesis/providers/base.py", line 84
        self._data: Dict[str, Any] = {}
                  ^
    SyntaxError: invalid syntax
[W 2019-03-11 16:04:47.344 SingleUserNotebookApp handlers:568] Unhandled error
```

**Comment by timkpaine** [comment]
Python 3.6+ only

**Comment by radumas** [comment]
ahhhhh
cheers
