### ISSUE TITLE
jupyter notebook and missing 'lantern.extensions.hideinput'

### ISSUE THREAD

**Issue by jarach** [timkpaine/lantern#198]
While opening a notebook in jupyter (not jupyterlab) getting error:
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'lantern.extensions.hideinput'
[E 22:46:05.329 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
      "Sec-Fetch-User": "?1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Referer": "http://localhost:8888/tree/Box%20Sync/WORKPLACE/Python%20Scripts",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,pl;q=0.8",
      "Cookie": "_xsrf=2|54cb2f39|d932ab571e996dbd75b1cf821fcecd73|1574974484; username-localhost-8888=\"2|1:0|10:1576187076|23:username-localhost-8888|44:ODRjZWViYWNlYjE3NDhhNmJmYTU3Y2E5NjEzM2EyYWY=|9b40ca3a86b7ba0c0d1dd373552cc37bb8f04ae8735e2552a5a5f1349a5faa17\"",
      "If-None-Match": "\"547509eded23a7210e91ac7965b6bc8adaba0ded\""
    }
[E 22:46:05.330 NotebookApp] 500 GET /notebooks/Box%20Sync/WORKPLACE/Python%20Scripts/Untitled.ipynb (::1) 34713.78ms referer=http://localhost:8888/tree/Box%20Sync/WORKPLACE/Python%20Scripts

Regards,
jarach

**Comment by timkpaine** [comment]
Looks like you updated to a later version (that removed lantern.extensions.hideinput) without modifying the serverextension. Try running `jupyter serverextension disable lantern.extensions.hideinput`

**Comment by jarach** [comment]
I installed pylantern in a new conda environment, run `jupyter serverextension disable lantern.extensions.hideinput` and still getting the error.

Beside question: is it possible use lantern with jupyter notebook?

Thx

**Comment by timkpaine** [comment]
This error doesn't actually affect any of lanterns other functionality. So the answer is yes, you won't see any difference other than the console message. But if you're still getting that message, you still have it enabled somewhere in your settings. Check `jupyter serverextension list` and also ensure that you don't have other configs in `jupyter --paths`

**Comment by jarach** [comment]
Thank you for the hint. I removed reference to the extension. I doesn't show up any more after running 'jupyter serverextension list'.
I re-installed pylantern.
Note: there is dependency to old version of plotly (plotly                    3.10.0                   pypi_0    pypi).

When I'm openning a notebook I'm getting this error message:

[I 17:09:06.728 NotebookApp] Creating new notebook in /Documents
[E 17:09:10.655 NotebookApp] Uncaught exception GET /notebooks/Documents/Untitled.ipynb?kernel_name=py36test (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Documents/Untitled.ipynb?kernel_name=py36test', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\tornado\gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\notebook\handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\base\handlers.py", line 507, in render_template
        return template.render(**ns)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\jinja2\environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\jinja2\_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\templates\notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\notebook\notebook\handlers.py", line 41, in get_frontend_exporters
        exporter_class = get_exporter(name)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\nbconvert\exporters\base.py", line 98, in get_exporter
        return entrypoints.get_single('nbconvert.exporters', name).load()
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\entrypoints.py", line 82, in load
        mod = import_module(self.module_name)
      File "C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'lantern.extensions.hideinput'

... and in the web browser:
![image](https://user-images.githubusercontent.com/58830859/73309815-054bd100-41f1-11ea-84c1-d525480a8371.png)


Any hint?

**Comment by timkpaine** [comment]
can you look for `entry_points.txt` in `C:\Users\108011367\AppData\Local\Continuum\anaconda3\envs\py36test\lib\site-packages\`. See if you have any out of date `pylantern...dist-info` lying around

**Comment by jarach** [comment]
I have found `entry_points.txt` in `c:\Users\108011367\appdata\Local\Continuum\anaconda3\envs\py36test\Lib\site-packages\pylantern-0.1.5.dist-info\` :
[nbconvert.exporters]
html_hidecode = lantern.extensions.hideinput.exporters:HTMLHideCodeExporter
pdf_hidecode = lantern.extensions.hideinput.exporters:PDFHideCodeExporter

I simply removed pylantern-0.1.5.dist-info and lantern folders and re-installed the package. The same file `entry_points.txt` with the same content appeared again.

**Comment by timkpaine** [comment]
bump to `0.1.6` and try again

**Comment by jarach** [comment]
The issue has been resolved with 0.1.6 version
